In [2]:
from keras.preprocessing.sequence import TimeseriesGenerator
import numpy as np

/home/mcicek/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [11]:
print(len(data))

56


In [12]:
print(len(data[:-(len(data)%timesteps)]))

50


In [17]:
-(len(data)%timesteps)

-6

In [19]:
data[:-(len(data)%timesteps)][-1]

array([49])

In [43]:
timesteps = 10
data = np.array([[i] for i in range(57)][:-1]+([[0.]]*timesteps))
labels = np.array(([[0.]]*timesteps)+[[i] for i in range(57)]+([[0.]]*timesteps))[1:]
targets = [labels[i:i+timesteps] for i in range(0, len(labels)-timesteps+1, timesteps)][:-1]
print(len(targets))#*timesteps
targets = np.array([targets[int(i/timesteps)] for i in range(len(targets)*(timesteps))])
print(targets.shape)
data_gen = TimeseriesGenerator(data[:-(len(data)%timesteps)], targets,
                                length=timesteps, sampling_rate=1, stride=timesteps,
                                batch_size=5)
batch_0 = data_gen[0]
x, y = batch_0

6
(60, 10, 1)


In [68]:
(5, 6)+(7, )

(5, 6, 7)

In [ ]:
img_gen = TimeseriesGenerator(inputMatrix, labels, length=timesteps, batch_size=batch_size)
ang_gen = TimeseriesGenerator(labels, labels, length=timesteps, batch_size=batch_size)

In [37]:
timesteps = 1
inputMatrix = np.array([[i] for i in range(57)])
labels = np.array([[i] for i in range(57)])
data_gen = TimeseriesGenerator(inputMatrix[1:], labels[:-1], 
                                length=timesteps, sampling_rate=1, stride=timesteps,
                                batch_size=5)
batch_0 = data_gen[0]
x, y = batch_0

In [38]:
#data[:-(len(data)%timesteps)]

In [9]:
def getSequencesToSequences(inputMatrix, labels):
    offset = labels.shape[0]%timesteps
    if offset > 0: offset = timesteps - offset
    npad = ((offset+1, timesteps), (0, 0), (0, 0), (0, 0))
    inputMatrix = np.pad(inputMatrix[1:], pad_width=npad, mode='constant', constant_values=0)
    npad = ((offset+1, timesteps), (0, 0))
    inputLabels = np.pad(labels[:-1], pad_width=npad, mode='constant', constant_values=0)
    npad = ((timesteps+offset+1, 0), (0, 0))
    targets = np.pad(labels[1:], pad_width=npad, mode='constant', constant_values=0)
    outputLabels = np.zeros(targets.shape[:1]+(timesteps,)+targets.shape[1:])
    il = np.zeros_like(inputLabels)
    for i in range(0, inputLabels.shape[0], timesteps):
        il[i] = inputLabels[i]
    inputLabels = il
    for i in range(0, len(targets), timesteps):
        outputLabels[i] = targets[i:i+timesteps] 
    return inputMatrix, inputLabels, outputLabels

timesteps = 10
inputMatrix = np.array([[[[i, i, i]]] for i in range(57)])
labels = np.array([[i, i, i] for i in range(57)])

inputMatrix, inputLabels, outputLabels = getSequencesToSequences(inputMatrix, labels)
    
img_gen = TimeseriesGenerator(inputMatrix, outputLabels, length=timesteps, sampling_rate=1, stride=timesteps, batch_size=6)
ang_gen = TimeseriesGenerator(inputLabels, outputLabels, length=timesteps, sampling_rate=1, stride=timesteps, batch_size=6)
batch_0 = img_gen[0]
batch_0 = ang_gen[0]
x, y = batch_0

In [10]:
x

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 6.,  6.,  6.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[16., 16., 16.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[26., 26., 26.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0., 

In [102]:
y

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 1.,  1.,  1.],
        [ 2.,  2.,  2.],
        [ 3.,  3.,  3.],
        [ 4.,  4.,  4.],
        [ 5.,  5.,  5.],
        [ 6.,  6.,  6.]],

       [[ 7.,  7.,  7.],
        [ 8.,  8.,  8.],
        [ 9.,  9.,  9.],
        [10., 10., 10.],
        [11., 11., 11.],
        [12., 12., 12.],
        [13., 13., 13.],
        [14., 14., 14.],
        [15., 15., 15.],
        [16., 16., 16.]],

       [[17., 17., 17.],
        [18., 18., 18.],
        [19., 19., 19.],
        [20., 20., 20.],
        [21., 21., 21.],
        [22., 22., 22.],
        [23., 23., 23.],
        [24., 24., 24.],
        [25., 25., 25.],
        [26., 26., 26.]],

       [[27., 27., 27.],
        [28., 28., 28.],
        [29., 29., 29.],
        [30., 30., 30.],
        [31., 31., 31.],
        [32., 32., 32.],
        [33., 33., 33.],
        [34., 34., 34.],
        [35., 35., 35.],
        [36., 36., 